# Generated by Django 6.0.4 on 2026-05-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_machine_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
